                                //Realizado por Andy Garcia 
//Declaracion del paquete vista.compras
package vista.compras_cxp;

//Importaciones de los archivos a utilizar
import Controlador.compras_cxp.Bodega;
import Modelo.compras_cxp.BodegaDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.util.HashMap;
import java.util.Map;

//Bitacora Implemenrada por Oscar Morales
import Controlador.seguridad.Bitacora;
import Controlador.seguridad.UsuarioConectado;

/**
 *
 * @author visitante
 */

//Declaracion de la clase mantenimiento proveedores
public class MantenimientoBodega extends javax.swing.JInternalFrame {
    
    //Codigo de la aplicacion mantenimiento proveedores
    final int APLICACION=202;
    
    //Metodo para el llenado de los combo box de los proveedores que existen
    public void llenadoDeCombos() {
        //Instancia de la clase proveedores
        BodegaDAO bodegaDAO = new BodegaDAO();
        //Se obteiene la lista de los proveedores
        List<Bodega> bodegas = bodegaDAO.select();
        //Mensaje al usuario
        cbox_proveedor.addItem("Seleccione una opción");
        //Ciclo que recorre y añade a cada proveedor al combo box
        for (int i = 0; i < bodegas.size(); i++) {
            cbox_proveedor.addItem(bodegas.get(i).getNombreBodega());
        }
    }
    
    //Metodo para el llenado de las tablas 
    public void llenadoDeTablas() {
        //Nuevo modelo para la tabla
        DefaultTableModel modelo = new DefaultTableModel();
        //Añadiendo columna del id del proveedor
        modelo.addColumn("Id ");
        //Añadiendo columna el nombre del proveedor
        modelo.addColumn("Nombre ");
        //Añadiendo columna de la dieccion del proveedor
        modelo.addColumn("Direccion ");
        //Añadiendo columna del numero de telefono del proveedor
        modelo.addColumn("tipo bodega ");
        //Añadiendo columna del id del email del proveedor
        modelo.addColumn("Estado ");
       
       
        //Instancia de la clase proveedor
        BodegaDAO bodegaDAO = new BodegaDAO();
        //Obteniendo la lista de los proveedores
        List<Bodega> bodegas = bodegaDAO.select();
        //Estableciendo el modelo en la tabla de vendedores
        tablaBodegas.setModel(modelo);
        // Arreglo temporal para almacenar los datos de cada fila
        String[] dato = new String[5];
        //Ciclo que recorre la lista obtenida  y agrega cada uno de los proveedores a la tabla
        for (int i = 0; i < bodegas.size(); i++) {
            dato[0] = bodegas.get(i).getId_bodega();
            dato[1] = bodegas.get(i).getNombreBodega();
            dato[2] = bodegas.get(i).getDireccionBodega();
            dato[3] = bodegas.get(i).getTipoBodega();
            dato[4] = bodegas.get(i).getEstadoBodega();
            //Agrega la fila al modelo
            modelo.addRow(dato);
        }
    }
    
    //Metodo para buscar un proveedor
    public void buscarProveedor() {
        //Se crea una instancia de la clase proveedor y su dao
        Bodega bodegaAConsultar = new Bodega();
        BodegaDAO proveedorDAO = new BodegaDAO();
        
         // Se establece el ID del proveedor a consultar desde el campo de texto
        bodegaAConsultar.setId_bodega(txtbuscado.getText());
        // Se realiza la consulta en la base de datos
        bodegaAConsultar = proveedorDAO.query(bodegaAConsultar);
        
        // Se llenan los campos con los datos del proveedor
        txtNombre.setText(bodegaAConsultar.getNombreBodega());
        txtDireccion.setText(bodegaAConsultar.getDireccionBodega());
        txtTipobodega.setText(bodegaAConsultar.getTipoBodega());
        txtestadobodega.setText(bodegaAConsultar.getEstadoBodega());
       
        
        //Se registra en la bitacora
        UsuarioConectado usuarioEnSesion = new UsuarioConectado();
        int resultadoBitacora=0;
        Bitacora bitacoraRegistro = new Bitacora();
        resultadoBitacora = bitacoraRegistro.setIngresarBitacora(usuarioEnSesion.getIdUsuario(), APLICACION,  "Consulta Datos Proveedores"); 
    }
       
    // Constructor del formulario Mantenimiento Proveedores
    public MantenimientoBodega() {
        //inicializacion de los componentes graficos
        initComponents();
        //Llamado al metodo de llenado de tablas
        llenadoDeTablas();
        //Llamado al metodo de llenado de los combo box
        llenadoDeCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        txtbuscado = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBodegas = new javax.swing.JTable();
        cbox_proveedor = new javax.swing.JComboBox<>();
        label4 = new javax.swing.JLabel();
        dire = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTipobodega = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtestadobodega = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtReporte = new javax.swing.JButton();
        txtAyuda = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento Proveedores");
        setVisible(true);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label1.setText("Proveedores - 202");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label3.setText("Nombre");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tablaBodegas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaBodegas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Proveedor", "Nombre Proveedor", "Direccion Proveedor", "Telefono Proveedor", "Email Proveedor", "Saldo Proveedor", "Estatus Proveedor", "Fecha Registro"
            }
        ));
        jScrollPane1.setViewportView(tablaBodegas);

        cbox_proveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbox_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_proveedorActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label4.setText("Proveedores");

        dire.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        dire.setText("Direccion");

        lb.setForeground(new java.awt.Color(204, 204, 204));
        lb.setText(".");

        jButton1.setText("jButton1");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Tipo");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Estado");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("ID");

        txtReporte.setText("Reporte");
        txtReporte.setEnabled(false);
        txtReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReporteActionPerformed(evt);
            }
        });

        txtAyuda.setText("Ayudas");
        txtAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(791, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(dire)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTipobodega, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(txtDireccion)
                    .addComponent(txtestadobodega)
                    .addComponent(txtID)
                    .addComponent(txtNombre))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(label1)
                                .addGap(294, 294, 294))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(190, 190, 190))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(label4)
                                        .addGap(18, 18, 18)))
                                .addComponent(cbox_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtReporte)
                                .addGap(48, 48, 48)
                                .addComponent(txtAyuda)))
                        .addContainerGap(130, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label4)
                                    .addComponent(cbox_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(label3)
                                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dire)
                                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTipobodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1)
                                        .addGap(13, 13, 13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtestadobodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(24, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)
                            .addComponent(btnLimpiar))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReporte)
                            .addComponent(txtAyuda))
                        .addGap(54, 54, 54))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Boton eliminar
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Instancia de la clase proveedor y su dato
        BodegaDAO bodegaDAO = new BodegaDAO();
        //Creacion de un objeto de la clase proveedor
        Bodega bodegaAEliminar = new Bodega();
        
        //Asignacion del id al proveedor que se desea eliminar
        bodegaAEliminar.setId_bodega(txtbuscado.getText());
        bodegaDAO.delete(bodegaAEliminar);
        //Llamado del llenado de tablas
        llenadoDeTablas();
        
        //Se registra en la bitacora
        UsuarioConectado usuarioEnSesion = new UsuarioConectado();
        int resultadoBitacora=0;
        Bitacora bitacoraRegistro = new Bitacora();
        resultadoBitacora = bitacoraRegistro.setIngresarBitacora(usuarioEnSesion.getIdUsuario(), APLICACION,  "Borrar Datos Proveedores");
    }//GEN-LAST:event_btnEliminarActionPerformed

    //Boton registrar
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
    //Instancia del proveedordao
    BodegaDAO bodegaDAO = new BodegaDAO();
    //Se crea un objeto del proveedor
    Bodega bodegaAInsertar = new Bodega(); 
        
        //Se asignan los valores de los campos de texto al objeto proveedor
        
        
        bodegaAInsertar.setId_bodega(txtID.getText());
        bodegaAInsertar.setNombreBodega(txtNombre.getText());
        bodegaAInsertar.setDireccionBodega(txtDireccion.getText());
        bodegaAInsertar.setTipoBodega(txtTipobodega.getText());
        bodegaAInsertar.setEstadoBodega(txtestadobodega.getText());
        
        //Se inserta el proveedor
        bodegaDAO.insert(bodegaAInsertar);
        
        //Se registra en la bitacora
        UsuarioConectado usuarioEnSesion = new UsuarioConectado();
        int resultadoBitacora=0;
        Bitacora bitacoraRegistro = new Bitacora();
        resultadoBitacora = bitacoraRegistro.setIngresarBitacora(usuarioEnSesion.getIdUsuario(), APLICACION,  "Ingreso Datos Proveedores");
        llenadoDeTablas();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    //Boton buscar
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Llamado del metodo buscar un proveedor
        buscarProveedor();
    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    
        //Se creau na instancia del proveedordao 
        BodegaDAO bodegaDAO = new BodegaDAO();
        //Se crea un objeto de la clase proveedor
        Bodega bodegaAActualizar = new Bodega();
        
        //Se establecen los valores desde los campos del formulario
        bodegaAActualizar.setId_bodega(txtbuscado.getText());
        bodegaAActualizar.setNombreBodega(txtNombre.getText());
        bodegaAActualizar.setDireccionBodega(txtDireccion.getText());
        bodegaAActualizar.setTipoBodega(txtTipobodega.getText());
        bodegaAActualizar.setEstadoBodega(txtestadobodega.getText());
        
        bodegaDAO.update(bodegaAActualizar);
        //Se llama el metodo de llenado de las tablas
        llenadoDeTablas();
        
        UsuarioConectado usuarioEnSesion = new UsuarioConectado();
        int resultadoBitacora=0;
        Bitacora bitacoraRegistro = new Bitacora();
        resultadoBitacora = bitacoraRegistro.setIngresarBitacora(usuarioEnSesion.getIdUsuario(), APLICACION,  "Actualizacion Datos Proveedores");
    }//GEN-LAST:event_btnModificarActionPerformed
    
    //Boton limpiar
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // Se restablece el ComboBox del proveedor al primer elemento
        cbox_proveedor.setSelectedIndex(0);
        //Se limpia los datos de los campos
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTipobodega.setText("");
        txtestadobodega.setText("");
        txtID.setText("");
        
        txtbuscado.setText("");
       
       
        //btnRegistrar.setEnabled(true);
        //btnModificar.setEnabled(true);
        //btnEliminar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbox_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_proveedorActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_proveedorActionPerformed
    
                //Serie de funciones publicas para Seguridad. Hecho por Pablo Palencia
    //Funciones publicas son llamadas cuando se crea la ventana para habilitar o desahibilitar botones
    
    //Se habilida el boton eliminar
    public void habilitarEliminar(boolean habilitado) {
        btnEliminar.setEnabled(habilitado);
    }
    
    //Se habilita el boton registrar
    public void habilitarRegistrar(boolean habilitado) {
        btnRegistrar.setEnabled(habilitado);
    }
    
    //Se habilita el boton buscar
    public void habilitarBuscar(boolean habilitado) {
        txtReporte.setEnabled(habilitado);
    }
    
    //Se habilita el boton modificar
    public void habilitarModificar(boolean habilitado) {
        btnModificar.setEnabled(habilitado);
    }
    
    //Boton reporte
    private void txtReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReporteActionPerformed
       /* //Instancia del proveedordao
        ProveedorDAO proveedorDAO = new ProveedorDAO();
        //Se llama el metodo para imprimir un reporte
        proveedorDAO.imprimirReporte(); 
        
        UsuarioConectado usuarioEnSesion = new UsuarioConectado();
        int resultadoBitacora=0;
        Bitacora bitacoraRegistro = new Bitacora();
        resultadoBitacora = bitacoraRegistro.setIngresarBitacora(usuarioEnSesion.getIdUsuario(), APLICACION,  "Visualizar reporte Proveedores");*/
    }//GEN-LAST:event_txtReporteActionPerformed
    
    //Boton ayuda
                         //Ayuda realizado por Andy Garcia
    private void txtAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAyudaActionPerformed
                        //ayuda implementada por Alisson López
       
        try {
            //Verificacion si el archivo de ayuda existe
            if ((new File("src\\main\\java\\ayudas\\ayudasComprasyCuentasPorPagar.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ayudas\\ayudasComprasyCuentasPorPagar.chm");
                p.waitFor();
            } else {
                //Muestra mensaje en consola si no se encuentra el archivo de ayuda
                System.out.println("La ayuda no Fue encontrada");
            }
            System.out.println("Correcto");
        } catch (Exception ex) {
            // En caso de error, imprime la traza para diagnóstico
            ex.printStackTrace();
        } 
        
        UsuarioConectado usuarioEnSesion = new UsuarioConectado();
        int resultadoBitacora=0;
        Bitacora bitacoraRegistro = new Bitacora();
        resultadoBitacora = bitacoraRegistro.setIngresarBitacora(usuarioEnSesion.getIdUsuario(), APLICACION,  "Gestion Ayuda Proveedores");
    }//GEN-LAST:event_txtAyudaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbox_proveedor;
    private javax.swing.JLabel dire;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaBodegas;
    private javax.swing.JButton txtAyuda;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JButton txtReporte;
    private javax.swing.JTextField txtTipobodega;
    private javax.swing.JTextField txtbuscado;
    private javax.swing.JTextField txtestadobodega;
    // End of variables declaration//GEN-END:variables
}
